import type { FormatPageData } from "@/lib/types";

export const formatPages: FormatPageData[] = [
  {
    slug: "corporate-kiosk",
    seoTitle: "Corporate Coffee Kiosk Service",
    category: "CORPORATE KIOSK",
    name: "Inside Tech Parks.",
    intro: "A fully managed coffee kiosk inside your office — set up, staffed, and restocked by MDP, every single day.",
    description: "MDP Coffee House's Corporate Kiosk format — a fully managed on-site coffee counter for offices and tech parks, staffed and operated end-to-end by MDP since 2005.",
    h2: "Corporate coffee kiosks, fully managed",
    paragraphs: [
      "The Corporate Kiosk is MDP's core format — a dedicated, fully staffed coffee counter set up inside your office or tech park campus. As an in-office coffee counter, MDP handles setup, daily staffing, restocking, and quality audits end-to-end, so your team gets consistent South Indian filter coffee without anyone on your side managing a vendor relationship day to day.",
      "This is the format used across the majority of MDP's enterprise partnerships — inside the campuses of technology companies, banks, and consulting firms nationwide. Each kiosk runs on the same standardised recipe and operating system MDP has used since 2005, regardless of city or client.",
    ],
    details: "SETUP · DAILY OPS · STAFF TRAINING · QUALITY AUDITS · RESTOCKING",
    photo: "/formats/corporatekiosk.png",
    solutions: [
      { title: "Corporate Managed Cafe", description: "MDP fully staffs and operates an in-office cafe setup exclusively for your workforce, not public footfall." },
      { title: "Pantry Services", description: "MDP manages your office pantry end-to-end — stock, restocking, consumables — so nothing runs out and nobody on your team manages a vendor relationship." },
      { title: "Beverage Solutions", description: "Full hot & cold beverage menu — filter coffee, tea, cold coffee, badam milk, and more — tailored to your workforce's preferences." },
      { title: "Snacks Solutions", description: "South Indian snacks and delicacies — sandwiches, bakery items, and more — tailored to your workforce's preferences." },
      { title: "24/7 Solutions", description: "Round-the-clock availability for offices operating outside standard hours." },
    ],
    closingStatement: "Whatever the challenge — a new office opening next week, a workforce that eats and drinks differently than most, hours no standard vendor will cover — MDP adapts the solution to fit. This is what twenty years of showing up has taught us.",
  },
  {
    slug: "qsr-cafe",
    seoTitle: "QSR Cafe for Malls & Co-Working Spaces",
    category: "QSR CAFE",
    name: "Where People Sit Down.",
    intro: "A full sit-down cafe experience for malls, food courts, and co-working spaces.",
    description: "MDP Coffee House's QSR Cafe format — a full sit-down cafe with a complete beverage menu, for malls, food courts, and co-working spaces.",
    h2: "Quick service coffee cafes for malls, food courts, and co-working spaces",
    paragraphs: [
      "The QSR Cafe format brings a complete sit-down cafe experience to malls, food courts, and co-working spaces. Guests can sit, order from a full beverage menu — filter coffee, badam milk, ginger tea, rose milk, and more — and stay.",
      "Unlike the Corporate Kiosk format, QSR Cafes are designed for public dine-in traffic rather than a single employer's workforce — the right format for malls, food courts, and co-working spaces where people come to sit and stay, distinct from Commercial Outlet's high-street and retail presence.",
    ],
    details: "FULL MENU · DINE-IN · HIGH VOLUME · MALLS · FOOD COURTS · CO-WORKING",
    photo: "/formats/qsr_cafe.png",
    expansionCta: {
      headline: "Know a Space That's Right for MDP?",
      body: "We're actively looking for new locations across India's malls, food courts, and co-working spaces. If you know a space that fits, or you're interested in franchising an MDP QSR Cafe, we'd like to hear from you.",
      ctaLabel: "Get in Touch",
      ctaHref: "/#contact",
    },
  },
  {
    slug: "commercial-outlet",
    seoTitle: "Commercial Outlet Coffee Service",
    category: "COMMERCIAL OUTLET",
    name: "Where India Gathers.",
    intro: "A commercial-format coffee counter for high-street and retail spaces — beyond the corporate campus.",
    description: "MDP Coffee House's Commercial Outlet format — filter coffee and South Indian snacks for high-street and commercial spaces, extending MDP's standard beyond the corporate campus since 2015.",
    h2: "Commercial outlets for high-street and retail spaces",
    paragraphs: [
      "The Commercial Outlet format is MDP's presence in the commercial and high-street spaces where India gathers, beyond the walls of a single office campus — stocked, managed, and restocked to the same standard MDP has run on since 2005.",
      "MDP first stepped beyond the corporate campus into commercial spaces in 2015, and added South Indian delicacies and snacks alongside its beverage menu from 2018 — a combination now available at outlets including Gandhinagar.",
    ],
    details: "SOUTH INDIAN SNACKS · FULL BEVERAGE MENU · HIGH-STREET PRESENCE · SINCE 2015",
    photo: "/formats/tuckshop.png",
    expansionCta: {
      headline: "Know a Space That's Right for MDP?",
      body: "We're actively looking for new commercial spaces across India — high-street locations, retail complexes, and the busy public spaces where people gather. If you have a space in mind, or you're interested in franchising an MDP Commercial Outlet, we'd like to hear from you.",
      ctaLabel: "Get in Touch",
      ctaHref: "/#contact",
    },
  },
  {
    slug: "event-catering",
    seoTitle: "Event Catering Coffee Service",
    category: "EVENT CATERING",
    name: "Ready For Any Event.",
    intro: "Wherever people gather, MDP is ready to pour — the same standard we've built over twenty years, brought straight to your event.",
    description: "MDP Coffee House's Event Catering format — coffee catering for every kind of gathering, from product launches and conferences to weddings, brought wherever the occasion calls for it.",
    h2: "Coffee catering for every kind of gathering",
    paragraphs: [
      "A product launch, a conference, a wedding, a campus fest — MDP's Event Catering brings the same filter coffee standard, made fresh and served warm, to wherever people are gathering. No occasion too big, no request too specific.",
      "This is twenty years of showing up, made mobile — no fixed kiosk, no standard menu, no infrastructure required. Give us the occasion, and we'll build the coffee experience around it.",
    ],
    details: "ANY OCCASION · CUSTOM MENUS · ZERO INFRASTRUCTURE · TWENTY YEARS OF SHOWING UP",
    photo: "/formats/mobilecart.png",
  },
];
