import type { Outlet } from "@/lib/types";

export const outlets: Outlet[] = [
  { client: "Amazon", clientSlug: "amazon", branch: "Taurus 3", city: "Bengaluru" },
  { client: "Amazon", clientSlug: "amazon", branch: "Building Aquila", city: "Bengaluru" },
  { client: "Amazon", clientSlug: "amazon", branch: "Taurus 2", city: "Bengaluru" },
  { client: "American Express", clientSlug: "amex", branch: "Bagmane", city: "Bengaluru" },
  { client: "American Express", clientSlug: "amex", branch: "Koramangala", city: "Bengaluru" },
  { client: "American Express", clientSlug: "amex", branch: "Luxor", city: "Bengaluru" },
  { client: "British Telecom", clientSlug: "british-telecom", branch: "Ecoworld", city: "Bengaluru" },
  { client: "British Telecom", clientSlug: "british-telecom", branch: "Ecospace", city: "Bengaluru" },
  { client: "Broadcom", clientSlug: "broadcom", branch: null, city: "Bengaluru" },
  { client: "Cognizant", clientSlug: "cognizant", branch: "Manyata Tech Park", city: "Bengaluru" },
  { client: "Cognizant", clientSlug: "cognizant", branch: "Bagmane - NEON", city: "Bengaluru" },
  { client: "Deutsche Bank", clientSlug: "deutsche-bank", branch: null, city: "Bengaluru" },
  { client: "Gandinagar", clientSlug: "gandinagar", branch: null, city: "Bengaluru" },
  { client: "HCL", clientSlug: "hcl", branch: null, city: "Bengaluru" },
  { client: "IBM", clientSlug: "ibm", branch: null, city: "Mysore" },
  { client: "IISER", clientSlug: "iiser-pune", branch: null, city: "Pune" },
  { client: "Infosys", clientSlug: "infosys", branch: "Building 47", city: "Bengaluru" },
  { client: "Infosys", clientSlug: "infosys", branch: "Equinox", city: "Bengaluru" },
  { client: "Infosys", clientSlug: "infosys", branch: "MNC", city: "Bengaluru" },
  { client: "Infosys", clientSlug: "infosys", branch: "GC2 Magna", city: "Mysore" },
  { client: "Infosys", clientSlug: "infosys", branch: "FC 5 Oasis", city: "Mysore" },
  { client: "Infosys", clientSlug: "infosys", branch: "FC 7 Feista Ground Floor", city: "Mysore" },
  { client: "Infosys", clientSlug: "infosys", branch: "FC 7 Feista", city: "Mysore" },
  { client: "Infosys", clientSlug: "infosys", branch: "Pocharam", city: "Hyderabad" },
  { client: "Infosys", clientSlug: "infosys", branch: "CPC", city: "Bengaluru" },
  { client: "Infosys", clientSlug: "infosys", branch: "B8 food court", city: "Bengaluru" },
  { client: "Infosys", clientSlug: "infosys", branch: "Pune Phase 2", city: "Pune" },
  { client: "Infosys", clientSlug: "infosys", branch: "North Gate", city: "Bengaluru" },
  { client: "Infosys", clientSlug: "infosys", branch: "Gachibowli", city: "Hyderabad" },
  { client: "Infosys", clientSlug: "infosys", branch: "Crescent", city: "Bengaluru" },
  { client: "Infosys", clientSlug: "infosys", branch: null, city: "Pune" },
  { client: "International Tech Park (ITPL)", clientSlug: "itpl", branch: "Ascendas Mall", city: "Bengaluru" },
  { client: "Kyndryl", clientSlug: "kyndryl", branch: null, city: "Bengaluru" },
  { client: "LG Soft", clientSlug: "lg-soft", branch: "Bellandur", city: "Bengaluru" },
  { client: "London Stock Exchange Group", clientSlug: "lsg", branch: "Bellandur", city: "Bengaluru" },
  { client: "London Stock Exchange Group", clientSlug: "lsg", branch: "RMZ", city: "Bengaluru" },
  { client: "Lowe's", clientSlug: "lowes", branch: "L2", city: "Bengaluru" },
  { client: "Lowe's", clientSlug: "lowes", branch: "D3", city: "Bengaluru" },
  { client: "Mall of Mysore", clientSlug: "mall-of-mysore", branch: null, city: "Mysore" },
  { client: "MiQ Digital", clientSlug: "miq-digital", branch: null, city: "Bengaluru" },
  { client: "Microsoft", clientSlug: "microsoft", branch: "Frans", city: "Bengaluru" },
  { client: "Microsoft", clientSlug: "microsoft", branch: "Luxor", city: "Bengaluru" },
  { client: "Microsoft", clientSlug: "microsoft", branch: "Cosmo", city: "Bengaluru" },
  { client: "Microsoft", clientSlug: "microsoft", branch: "B4", city: "Hyderabad" },
  { client: "Microsoft", clientSlug: "microsoft", branch: "Phoenix", city: "Hyderabad" },
  { client: "Mu Sigma", clientSlug: "mu-sigma", branch: null, city: "Bengaluru" },
  { client: "Nexus Mall", clientSlug: "nexus-mall", branch: "Mysore", city: "Bengaluru" },
  { client: "Oracle", clientSlug: "oracle", branch: "Krishna Magnum", city: "Bengaluru" },
  { client: "Oracle", clientSlug: "oracle", branch: "Oracle Tech Park", city: "Bengaluru" },
  { client: "Oracle", clientSlug: "oracle", branch: "Oracle Tech Hub (A Block)", city: "Bengaluru" },
  { client: "Oracle", clientSlug: "oracle", branch: "Oracle Tech Hub (Tower C)", city: "Bengaluru" },
  { client: "Oracle", clientSlug: "oracle", branch: "Oracle Tech Hub B Block", city: "Bengaluru" },
  { client: "PVR", clientSlug: "pvr", branch: null, city: "Mysore" },
  { client: "Philips", clientSlug: "philips", branch: "Prana", city: "Bengaluru" },
  { client: "Samsung", clientSlug: "samsung", branch: "Phoenix", city: "Bengaluru" },
  { client: "Smartworks", clientSlug: "smart-work", branch: null, city: "Bengaluru" },
  { client: "Societe Generale", clientSlug: "societe-generale", branch: "Bellandur", city: "Bengaluru" },
  { client: "Societe Generale", clientSlug: "societe-generale", branch: "ITPL", city: "Bengaluru" },
  { client: "Societe Generale", clientSlug: "societe-generale", branch: "Victor", city: "Bengaluru" },
  { client: "TCS", clientSlug: "tcs", branch: "H Block", city: "Bengaluru" },
  { client: "TCS", clientSlug: "tcs", branch: "Pioneer", city: "Bengaluru" },
  { client: "TCS", clientSlug: "tcs", branch: "Bhuwalka", city: "Bengaluru" },
  { client: "TCS", clientSlug: "tcs", branch: "Yashwanthpura", city: "Bengaluru" },
  { client: "Tecnotree", clientSlug: "tecnotree", branch: null, city: "Bengaluru" },
  { client: "Tesco", clientSlug: "tesco", branch: "BLR", city: "Bengaluru" },
  { client: "Thomson Reuters", clientSlug: "thomson-reuters", branch: null, city: "Bengaluru" },
  { client: "Wells Fargo", clientSlug: "wells-fargo", branch: null, city: "Hyderabad" },
  { client: "Wells Fargo", clientSlug: "wells-fargo", branch: null, city: "Bengaluru" },
  { client: "Wells Fargo", clientSlug: "wells-fargo", branch: "BLR - Petunia", city: "Bengaluru" },
];
